networks:
  proxy:
    external: true

volumes:
  conf:
    external: true
  vhost:
    external: true
  html:
    external: true
  certs:
    external: true
  acme:
    external: true


services:
  nginx-proxy:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /run/user/1000/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - DEFAULT_EMAIL=${EMAIL}
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - proxy
    depends_on:
      - nginx-proxy
    links:
      - nginx-proxy

#  dockergen:
#    image: nginxproxy/docker-gen
#    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
#    volumes_from:
#      - nginx-proxy
#    volumes:
#      - /run/user/1000/docker.sock:/tmp/docker.sock:ro
#      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
#    networks:
#      - proxy
